name: Issue Auto Reply

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request == null }}
    steps:
      - name: Post welcome comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const message = `Thank you for raising this issue! Our team will review it soon.

For more queries or discussions or approval of requests, please join the Discord server for further discussion: https://discord.com/invite/Yn9g6KuWyA`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: message
            });
